### ISSUE TITLE
Morning session peer-to-peer code review

### ISSUE THREAD

**Issue by Besufekad-HAZ** [stephenkati/Global-Canvas-Art-Exhibition-Concert-#2]
- **All things look nice and great design implementation. but there are some minor things to work on.**
- It's a best practice to avoid using fixed height because It can affect the responsiveness of your page
https://github.com/stephenkati/Global-Canvas-Art-Exhibition-Concert-/blob/edc19ce3603f9db4cda9683a1bc7e8fa9e4fce91/css/style.css#L112 
-Although the current layout is great and responsive it would be great to use 2 columns just above 768px(screen size) as per the template design by Cindy Shin (https://www.behance.net/adagio07).
https://github.com/stephenkati/Global-Canvas-Art-Exhibition-Concert-/blob/edc19ce3603f9db4cda9683a1bc7e8fa9e4fce91/css/style.css#L736-L745

**Comment by stephenkati** [comment]
Glad you let me know. Issue fixed
